-- books table

insert into books (id, title, isbn_10, isbn_13, pages, language, cover_image, publication_date, summary, updated_at) values ('01J7W030NT4ZGQEXB6X8241VPG', 'Welcome to Mooseport', NULL, '596868118-7', 406, 'French', 'http://ft.com/euismod.xml?feugiat=ac&non=nibh&pretium=fusce&quis=lacus&lectus=purus&suspendisse=aliquet&potenti=at&in=feugiat&eleifend=non&quam=pretium&a=quis&odio=lectus', '6/8/2019', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', '2023-11-01T20:25:54Z');
insert into books (id, title, isbn_10, isbn_13, pages, language, cover_image, publication_date, summary, updated_at) values ('01J7W030W6G4C92QX73SZ8HW3A', 'Snow Dogs', NULL, '769421126-1', 4507, 'Albanian', 'http://google.co.jp/vel/ipsum.js?praesent=sapien&blandit=quis&lacinia=libero&erat=nullam&vestibulum=sit&sed=amet&magna=turpis&at=elementum&nunc=ligula&commodo=vehicula&placerat=consequat&praesent=morbi&blandit=a&nam=ipsum&nulla=integer&integer=a&pede=nibh&justo=in&lacinia=quis&eget=justo&tincidunt=maecenas&eget=rhoncus&tempus=aliquam&vel=lacus&pede=morbi&morbi=quis&porttitor=tortor&lorem=id&id=nulla&ligula=ultrices&suspendisse=aliquet&ornare=maecenas&consequat=leo&lectus=odio&in=condimentum&est=id&risus=luctus&auctor=nec&sed=molestie&tristique=sed&in=justo&tempus=pellentesque', '10/15/2009', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.

Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2024-03-08T23:05:20Z');
insert into books (id, title, isbn_10, isbn_13, pages, language, cover_image, publication_date, summary, updated_at) values ('01J7W030W86V1WTVBYSRP79APE', 'Buster', '827354773-6', '347938560-5', 8744, 'Irish Gaelic', 'https://angelfire.com/ut/rhoncus/aliquet.html?donec=vel&odio=nisl&justo=duis&sollicitudin=ac&ut=nibh&suscipit=fusce&a=lacus&feugiat=purus&et=aliquet&eros=at&vestibulum=feugiat&ac=non&est=pretium&lacinia=quis&nisi=lectus&venenatis=suspendisse&tristique=potenti&fusce=in&congue=eleifend&diam=quam&id=a&ornare=odio&imperdiet=in&sapien=hac&urna=habitasse&pretium=platea&nisl=dictumst&ut=maecenas&volutpat=ut&sapien=massa&arcu=quis&sed=augue&augue=luctus&aliquam=tincidunt&erat=nulla&volutpat=mollis&in=molestie&congue=lorem&etiam=quisque&justo=ut&etiam=erat&pretium=curabitur&iaculis=gravida&justo=nisi&in=at&hac=nibh&habitasse=in&platea=hac&dictumst=habitasse&etiam=platea&faucibus=dictumst&cursus=aliquam&urna=augue&ut=quam&tellus=sollicitudin&nulla=vitae&ut=consectetuer&erat=eget&id=rutrum&mauris=at&vulputate=lorem&elementum=integer&nullam=tincidunt&varius=ante&nulla=vel&facilisi=ipsum&cras=praesent&non=blandit&velit=lacinia&nec=erat&nisi=vestibulum&vulputate=sed&nonummy=magna&maecenas=at&tincidunt=nunc&lacus=commodo', '8/24/2008', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', '2023-09-30T22:19:06Z');
insert into books (id, title, isbn_10, isbn_13, pages, language, cover_image, publication_date, summary, updated_at) values ('01J7W030W97E1XPTFS0ZCF5Y9P', 'Ratatouille', '700522412-4', '846555607-5', 8591, 'Northern Sotho', 'http://rakuten.co.jp/integer/ac/neque/duis/bibendum/morbi/non.js?lorem=accumsan&vitae=felis&mattis=ut&nibh=at&ligula=dolor&nec=quis&sem=odio&duis=consequat&aliquam=varius&convallis=integer&nunc=ac&proin=leo&at=pellentesque&turpis=ultrices&a=mattis&pede=odio&posuere=donec&nonummy=vitae&integer=nisi&non=nam&velit=ultrices&donec=libero&diam=non&neque=mattis&vestibulum=pulvinar&eget=nulla&vulputate=pede&ut=ullamcorper&ultrices=augue&vel=a&augue=suscipit&vestibulum=nulla&ante=elit&ipsum=ac&primis=nulla&in=sed&faucibus=vel&orci=enim&luctus=sit&et=amet&ultrices=nunc&posuere=viverra&cubilia=dapibus&curae=nulla&donec=suscipit&pharetra=ligula&magna=in&vestibulum=lacus&aliquet=curabitur&ultrices=at&erat=ipsum&tortor=ac&sollicitudin=tellus&mi=semper&sit=interdum&amet=mauris&lobortis=ullamcorper&sapien=purus&sapien=sit&non=amet&mi=nulla&integer=quisque&ac=arcu&neque=libero&duis=rutrum&bibendum=ac', '10/11/2013', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2023-10-04T11:40:27Z');
insert into books (id, title, isbn_10, isbn_13, pages, language, cover_image, publication_date, summary, updated_at) values ('01J7W030WB33P57PYTK6R7WRR7', 'Like Crazy', '697535088-4', '214399642-X', 8662, 'Dzongkha', 'https://ca.gov/consequat/dui/nec.xml?pede=quis&justo=turpis&eu=sed&massa=ante&donec=vivamus&dapibus=tortor&duis=duis&at=mattis&velit=egestas&eu=metus&est=aenean&congue=fermentum&elementum=donec&in=ut&hac=mauris&habitasse=eget&platea=massa&dictumst=tempor&morbi=convallis&vestibulum=nulla&velit=neque&id=libero&pretium=convallis&iaculis=eget&diam=eleifend&erat=luctus&fermentum=ultricies&justo=eu&nec=nibh&condimentum=quisque&neque=id&sapien=justo&placerat=sit&ante=amet&nulla=sapien&justo=dignissim&aliquam=vestibulum&quis=vestibulum&turpis=ante&eget=ipsum', '4/28/2015', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2024-04-05T10:00:24Z');
insert into books (id, title, isbn_10, isbn_13, pages, language, cover_image, publication_date, summary, updated_at) values ('01J7W030WE7PFAM58P3DBAHYEM', 'My Best Friend''s Girl', NULL, '436323855-0', 9990, 'Marathi', 'http://cnbc.com/purus/phasellus/in/felis.jpg?interdum=metus&eu=sapien&tincidunt=ut&in=nunc&leo=vestibulum&maecenas=ante&pulvinar=ipsum&lobortis=primis&est=in&phasellus=faucibus&sit=orci&amet=luctus&erat=et&nulla=ultrices&tempus=posuere&vivamus=cubilia&in=curae', '5/5/2002', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.

In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '2023-11-26T01:17:41Z');
insert into books (id, title, isbn_10, isbn_13, pages, language, cover_image, publication_date, summary, updated_at) values ('01J7W030WG1MQ7NEZEMY3Q0D9Z', 'Dear Pillow', '275799739-4', '781100078-4', 3982, 'Marathi', 'http://unblog.fr/scelerisque/mauris/sit/amet.html?praesent=ultrices&id=posuere&massa=cubilia&id=curae&nisl=nulla&venenatis=dapibus&lacinia=dolor&aenean=vel&sit=est&amet=donec&justo=odio&morbi=justo&ut=sollicitudin&odio=ut&cras=suscipit', '3/12/2018', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', '2023-09-21T20:59:28Z');
insert into books (id, title, isbn_10, isbn_13, pages, language, cover_image, publication_date, summary, updated_at) values ('01J7W030WJY05V9C8TSQ7T7F8B', 'Poolsite', '397619451-4', '363479978-1', 1951, 'Zulu', 'http://pbs.org/donec/ut.json?ut=vel&ultrices=est&vel=donec&augue=odio&vestibulum=justo&ante=sollicitudin&ipsum=ut&primis=suscipit&in=a&faucibus=feugiat&orci=et&luctus=eros&et=vestibulum&ultrices=ac&posuere=est&cubilia=lacinia&curae=nisi&donec=venenatis&pharetra=tristique&magna=fusce&vestibulum=congue&aliquet=diam&ultrices=id&erat=ornare&tortor=imperdiet&sollicitudin=sapien&mi=urna&sit=pretium&amet=nisl&lobortis=ut&sapien=volutpat&sapien=sapien&non=arcu&mi=sed&integer=augue&ac=aliquam&neque=erat&duis=volutpat&bibendum=in&morbi=congue&non=etiam&quam=justo&nec=etiam&dui=pretium&luctus=iaculis&rutrum=justo&nulla=in&tellus=hac&in=habitasse&sagittis=platea&dui=dictumst&vel=etiam&nisl=faucibus&duis=cursus&ac=urna&nibh=ut&fusce=tellus&lacus=nulla&purus=ut&aliquet=erat&at=id&feugiat=mauris&non=vulputate&pretium=elementum&quis=nullam&lectus=varius&suspendisse=nulla&potenti=facilisi&in=cras&eleifend=non&quam=velit&a=nec&odio=nisi&in=vulputate&hac=nonummy&habitasse=maecenas&platea=tincidunt&dictumst=lacus&maecenas=at&ut=velit&massa=vivamus&quis=vel&augue=nulla&luctus=eget&tincidunt=eros&nulla=elementum&mollis=pellentesque&molestie=quisque&lorem=porta&quisque=volutpat&ut=erat&erat=quisque', '9/20/2023', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.', '2023-10-20T23:06:47Z');
insert into books (id, title, isbn_10, isbn_13, pages, language, cover_image, publication_date, summary, updated_at) values ('01J7W030WMH7SPERF9PDZ4B27W', 'Surviving Picasso', '735686290-5', '160903129-6', 8403, 'Catalan', 'https://stanford.edu/tellus/nulla/ut/erat/id/mauris.json?volutpat=praesent&dui=lectus&maecenas=vestibulum&tristique=quam&est=sapien', '9/27/2020', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.', '2023-10-13T17:40:54Z');
insert into books (id, title, isbn_10, isbn_13, pages, language, cover_image, publication_date, summary, updated_at) values ('01J7W030WPC54NW84W3EATZ714', 'The Brain', '831208056-2', '050403562-2', 3151, 'Burmese', 'https://columbia.edu/fusce/posuere/felis/sed/lacus/morbi/sem.js?ipsum=gravida&aliquam=sem&non=praesent&mauris=id&morbi=massa&non=id&lectus=nisl&aliquam=venenatis&sit=lacinia&amet=aenean&diam=sit&in=amet&magna=justo&bibendum=morbi&imperdiet=ut&nullam=odio&orci=cras&pede=mi&venenatis=pede&non=malesuada&sodales=in&sed=imperdiet&tincidunt=et&eu=commodo&felis=vulputate&fusce=justo&posuere=in&felis=blandit&sed=ultrices', '9/11/2018', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', '2024-03-15T03:08:09Z');

-- Authors Table

insert into authors (id, first_name, last_name, cover_image, bio, updated_at) values ('01J7W089DNEHP4DTR8RVXSENA3', 'Dina', 'Buckthorp', 'https://macromedia.com/et/ultrices/posuere/cubilia/curae/mauris.json?ut=eget&suscipit=congue&a=eget&feugiat=semper&et=rutrum&eros=nulla&vestibulum=nunc&ac=purus&est=phasellus&lacinia=in&nisi=felis&venenatis=donec&tristique=semper&fusce=sapien&congue=a&diam=libero&id=nam&ornare=dui&imperdiet=proin&sapien=leo&urna=odio&pretium=porttitor&nisl=id&ut=consequat&volutpat=in&sapien=consequat&arcu=ut&sed=nulla&augue=sed&aliquam=accumsan&erat=felis&volutpat=ut&in=at&congue=dolor&etiam=quis&justo=odio&etiam=consequat&pretium=varius', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.

Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', '2004-02-10T16:09:09Z');
insert into authors (id, first_name, last_name, cover_image, bio, updated_at) values ('01J7W089DP1JVAA1MKESKGKWHA', 'Kristoforo', 'Balsillie', 'http://samsung.com/eget/tincidunt/eget/tempus/vel/pede.json?nullam=morbi&sit=odio&amet=odio&turpis=elementum&elementum=eu&ligula=interdum&vehicula=eu&consequat=tincidunt&morbi=in&a=leo&ipsum=maecenas&integer=pulvinar&a=lobortis&nibh=est&in=phasellus&quis=sit&justo=amet&maecenas=erat&rhoncus=nulla&aliquam=tempus&lacus=vivamus&morbi=in&quis=felis&tortor=eu&id=sapien&nulla=cursus&ultrices=vestibulum&aliquet=proin&maecenas=eu&leo=mi&odio=nulla&condimentum=ac&id=enim&luctus=in&nec=tempor&molestie=turpis&sed=nec&justo=euismod&pellentesque=scelerisque&viverra=quam&pede=turpis&ac=adipiscing&diam=lorem&cras=vitae&pellentesque=mattis&volutpat=nibh&dui=ligula&maecenas=nec&tristique=sem&est=duis&et=aliquam&tempus=convallis&semper=nunc&est=proin&quam=at&pharetra=turpis&magna=a&ac=pede&consequat=posuere&metus=nonummy&sapien=integer&ut=non&nunc=velit&vestibulum=donec&ante=diam&ipsum=neque&primis=vestibulum&in=eget&faucibus=vulputate', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', '2013-07-07T08:17:49Z');
insert into authors (id, first_name, last_name, cover_image, bio, updated_at) values ('01J7W089DQ0GJV81NSA9J4W1G9', 'Pacorro', 'Massel', 'https://quantcast.com/mauris/laoreet/ut/rhoncus/aliquet/pulvinar/sed.js?cursus=ante&vestibulum=ipsum&proin=primis&eu=in&mi=faucibus&nulla=orci&ac=luctus&enim=et&in=ultrices&tempor=posuere&turpis=cubilia&nec=curae&euismod=nulla&scelerisque=dapibus&quam=dolor&turpis=vel', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2020-07-03T05:10:38Z');
insert into authors (id, first_name, last_name, cover_image, bio, updated_at) values ('01J7W089DR4MSS93FM1B2PPK1N', 'Peder', 'Maywood', 'http://tripod.com/curabitur/convallis/duis/consequat/dui.jpg?justo=cursus&etiam=urna&pretium=ut&iaculis=tellus&justo=nulla&in=ut&hac=erat&habitasse=id&platea=mauris&dictumst=vulputate&etiam=elementum&faucibus=nullam&cursus=varius&urna=nulla&ut=facilisi&tellus=cras&nulla=non&ut=velit&erat=nec&id=nisi&mauris=vulputate&vulputate=nonummy&elementum=maecenas&nullam=tincidunt&varius=lacus&nulla=at&facilisi=velit&cras=vivamus&non=vel&velit=nulla&nec=eget&nisi=eros&vulputate=elementum&nonummy=pellentesque&maecenas=quisque&tincidunt=porta&lacus=volutpat&at=erat&velit=quisque&vivamus=erat&vel=eros&nulla=viverra&eget=eget&eros=congue&elementum=eget&pellentesque=semper&quisque=rutrum&porta=nulla&volutpat=nunc&erat=purus&quisque=phasellus&erat=in&eros=felis&viverra=donec&eget=semper&congue=sapien&eget=a&semper=libero&rutrum=nam&nulla=dui&nunc=proin&purus=leo&phasellus=odio&in=porttitor&felis=id&donec=consequat&semper=in&sapien=consequat&a=ut&libero=nulla&nam=sed&dui=accumsan&proin=felis&leo=ut&odio=at&porttitor=dolor&id=quis&consequat=odio&in=consequat&consequat=varius&ut=integer&nulla=ac&sed=leo&accumsan=pellentesque&felis=ultrices&ut=mattis&at=odio&dolor=donec&quis=vitae&odio=nisi', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', '2007-10-31T10:34:31Z');
insert into authors (id, first_name, last_name, cover_image, bio, updated_at) values ('01J7W089DSSBMZFV81KQ0HSE1X', 'Honey', 'Davet', 'https://youtu.be/et/tempus.js?eros=libero&elementum=convallis&pellentesque=eget&quisque=eleifend&porta=luctus&volutpat=ultricies&erat=eu&quisque=nibh&erat=quisque&eros=id&viverra=justo&eget=sit&congue=amet&eget=sapien&semper=dignissim&rutrum=vestibulum&nulla=vestibulum&nunc=ante&purus=ipsum&phasellus=primis&in=in&felis=faucibus&donec=orci&semper=luctus&sapien=et&a=ultrices&libero=posuere&nam=cubilia&dui=curae&proin=nulla&leo=dapibus&odio=dolor&porttitor=vel&id=est&consequat=donec&in=odio&consequat=justo&ut=sollicitudin&nulla=ut&sed=suscipit&accumsan=a&felis=feugiat&ut=et&at=eros&dolor=vestibulum&quis=ac&odio=est&consequat=lacinia&varius=nisi&integer=venenatis&ac=tristique&leo=fusce&pellentesque=congue&ultrices=diam&mattis=id&odio=ornare&donec=imperdiet&vitae=sapien&nisi=urna&nam=pretium&ultrices=nisl&libero=ut&non=volutpat&mattis=sapien&pulvinar=arcu&nulla=sed&pede=augue&ullamcorper=aliquam&augue=erat&a=volutpat&suscipit=in&nulla=congue&elit=etiam&ac=justo&nulla=etiam&sed=pretium&vel=iaculis&enim=justo&sit=in&amet=hac&nunc=habitasse&viverra=platea&dapibus=dictumst&nulla=etiam&suscipit=faucibus&ligula=cursus&in=urna&lacus=ut', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', '2012-02-21T00:19:38Z');
insert into authors (id, first_name, last_name, cover_image, bio, updated_at) values ('01J7W089DT8CZFDAQTSMA1TP9S', 'Vittoria', 'Pigford', 'http://statcounter.com/eget/elit/sodales/scelerisque.xml?sagittis=rhoncus&nam=mauris&congue=enim&risus=leo&semper=rhoncus&porta=sed&volutpat=vestibulum&quam=sit&pede=amet&lobortis=cursus&ligula=id&sit=turpis&amet=integer&eleifend=aliquet&pede=massa&libero=id&quis=lobortis', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', '2020-06-18T12:12:43Z');
insert into authors (id, first_name, last_name, cover_image, bio, updated_at) values ('01J7W089DV74SHZJAGMXP32VE5', 'Sydney', 'Brandoni', 'https://list-manage.com/iaculis/diam/erat/fermentum/justo/nec/condimentum.json?luctus=lacus&et=morbi&ultrices=sem&posuere=mauris&cubilia=laoreet&curae=ut&donec=rhoncus&pharetra=aliquet&magna=pulvinar&vestibulum=sed&aliquet=nisl&ultrices=nunc&erat=rhoncus&tortor=dui&sollicitudin=vel&mi=sem&sit=sed&amet=sagittis&lobortis=nam&sapien=congue&sapien=risus&non=semper&mi=porta&integer=volutpat&ac=quam&neque=pede&duis=lobortis&bibendum=ligula&morbi=sit&non=amet&quam=eleifend&nec=pede&dui=libero&luctus=quis&rutrum=orci&nulla=nullam&tellus=molestie&in=nibh&sagittis=in&dui=lectus&vel=pellentesque&nisl=at&duis=nulla&ac=suspendisse&nibh=potenti&fusce=cras&lacus=in', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', '2017-12-06T20:17:28Z');
insert into authors (id, first_name, last_name, cover_image, bio, updated_at) values ('01J7W089DW2A8ZKA7NF4WN14FB', 'Tonya', 'Baber', 'http://tuttocitta.it/tempus/sit/amet/sem/fusce.png?in=libero&felis=non&donec=mattis&semper=pulvinar&sapien=nulla&a=pede&libero=ullamcorper&nam=augue&dui=a&proin=suscipit&leo=nulla&odio=elit&porttitor=ac&id=nulla&consequat=sed&in=vel&consequat=enim&ut=sit&nulla=amet&sed=nunc&accumsan=viverra&felis=dapibus&ut=nulla&at=suscipit&dolor=ligula&quis=in&odio=lacus&consequat=curabitur&varius=at&integer=ipsum&ac=ac&leo=tellus&pellentesque=semper&ultrices=interdum&mattis=mauris&odio=ullamcorper&donec=purus&vitae=sit&nisi=amet&nam=nulla&ultrices=quisque&libero=arcu&non=libero', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2016-01-28T19:15:44Z');
insert into authors (id, first_name, last_name, cover_image, bio, updated_at) values ('01J7W089DXVYK3Z07M6HYN4XKF', 'Nappy', 'Saffill', 'http://google.com.hk/sit/amet/consectetuer/adipiscing/elit/proin/interdum.xml?leo=vestibulum&maecenas=proin&pulvinar=eu&lobortis=mi&est=nulla&phasellus=ac&sit=enim&amet=in&erat=tempor&nulla=turpis&tempus=nec&vivamus=euismod&in=scelerisque&felis=quam&eu=turpis&sapien=adipiscing&cursus=lorem&vestibulum=vitae&proin=mattis&eu=nibh&mi=ligula&nulla=nec&ac=sem&enim=duis&in=aliquam&tempor=convallis&turpis=nunc&nec=proin&euismod=at&scelerisque=turpis&quam=a&turpis=pede&adipiscing=posuere&lorem=nonummy&vitae=integer&mattis=non&nibh=velit&ligula=donec&nec=diam&sem=neque&duis=vestibulum&aliquam=eget&convallis=vulputate&nunc=ut&proin=ultrices&at=vel&turpis=augue&a=vestibulum&pede=ante&posuere=ipsum&nonummy=primis&integer=in&non=faucibus&velit=orci&donec=luctus&diam=et&neque=ultrices&vestibulum=posuere&eget=cubilia&vulputate=curae&ut=donec&ultrices=pharetra&vel=magna&augue=vestibulum&vestibulum=aliquet&ante=ultrices&ipsum=erat&primis=tortor&in=sollicitudin&faucibus=mi&orci=sit&luctus=amet&et=lobortis&ultrices=sapien&posuere=sapien&cubilia=non&curae=mi&donec=integer&pharetra=ac&magna=neque', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2013-04-06T23:04:39Z');
insert into authors (id, first_name, last_name, cover_image, bio, updated_at) values ('01J7W089DY4BER9XYFQN4MNYFB', 'Linc', 'Poyser', 'https://businessinsider.com/ac/est/lacinia/nisi/venenatis/tristique/fusce.jpg?faucibus=in&orci=faucibus&luctus=orci&et=luctus&ultrices=et&posuere=ultrices&cubilia=posuere&curae=cubilia&nulla=curae&dapibus=donec&dolor=pharetra&vel=magna&est=vestibulum&donec=aliquet&odio=ultrices&justo=erat&sollicitudin=tortor&ut=sollicitudin&suscipit=mi&a=sit&feugiat=amet&et=lobortis&eros=sapien&vestibulum=sapien&ac=non&est=mi&lacinia=integer&nisi=ac&venenatis=neque&tristique=duis&fusce=bibendum&congue=morbi&diam=non&id=quam&ornare=nec&imperdiet=dui&sapien=luctus&urna=rutrum&pretium=nulla&nisl=tellus&ut=in&volutpat=sagittis&sapien=dui&arcu=vel&sed=nisl&augue=duis&aliquam=ac&erat=nibh&volutpat=fusce&in=lacus&congue=purus&etiam=aliquet&justo=at&etiam=feugiat&pretium=non&iaculis=pretium&justo=quis&in=lectus&hac=suspendisse&habitasse=potenti&platea=in&dictumst=eleifend&etiam=quam&faucibus=a&cursus=odio&urna=in&ut=hac&tellus=habitasse&nulla=platea&ut=dictumst&erat=maecenas&id=ut&mauris=massa&vulputate=quis&elementum=augue&nullam=luctus&varius=tincidunt&nulla=nulla&facilisi=mollis&cras=molestie&non=lorem&velit=quisque&nec=ut&nisi=erat&vulputate=curabitur&nonummy=gravida&maecenas=nisi&tincidunt=at', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', '2014-06-09T11:27:16Z');

-- Publishers Table

insert into publishers (id, name, address, website, updated_at) values ('01J7W0QK1V8415VZ4X8NFFD9ME', 'Renner-MacGyver', '03638 Dunning Road', 'https://infoseek.co.jp/metus/aenean/fermentum/donec.js?in=dapibus&quis=dolor&justo=vel&maecenas=est&rhoncus=donec&aliquam=odio&lacus=justo&morbi=sollicitudin&quis=ut&tortor=suscipit&id=a&nulla=feugiat&ultrices=et&aliquet=eros&maecenas=vestibulum&leo=ac&odio=est&condimentum=lacinia&id=nisi&luctus=venenatis&nec=tristique&molestie=fusce&sed=congue&justo=diam&pellentesque=id&viverra=ornare&pede=imperdiet&ac=sapien&diam=urna&cras=pretium&pellentesque=nisl&volutpat=ut&dui=volutpat&maecenas=sapien&tristique=arcu&est=sed&et=augue&tempus=aliquam&semper=erat&est=volutpat', '2024-06-25T23:36:52Z');
insert into publishers (id, name, address, website, updated_at) values ('01J7W0QK1WF4SQ43493203945Z', 'Lubowitz Group', '0390 Acker Place', 'https://house.gov/vel/enim/sit/amet/nunc/viverra/dapibus.jsp?nullam=aenean&sit=fermentum&amet=donec&turpis=ut&elementum=mauris&ligula=eget&vehicula=massa&consequat=tempor&morbi=convallis&a=nulla&ipsum=neque&integer=libero&a=convallis&nibh=eget&in=eleifend&quis=luctus&justo=ultricies&maecenas=eu&rhoncus=nibh&aliquam=quisque&lacus=id&morbi=justo&quis=sit&tortor=amet&id=sapien&nulla=dignissim&ultrices=vestibulum&aliquet=vestibulum&maecenas=ante&leo=ipsum&odio=primis&condimentum=in&id=faucibus&luctus=orci&nec=luctus&molestie=et&sed=ultrices&justo=posuere&pellentesque=cubilia&viverra=curae&pede=nulla&ac=dapibus&diam=dolor&cras=vel&pellentesque=est&volutpat=donec&dui=odio&maecenas=justo&tristique=sollicitudin&est=ut&et=suscipit&tempus=a&semper=feugiat&est=et&quam=eros&pharetra=vestibulum&magna=ac&ac=est&consequat=lacinia&metus=nisi&sapien=venenatis&ut=tristique&nunc=fusce&vestibulum=congue&ante=diam&ipsum=id&primis=ornare&in=imperdiet&faucibus=sapien&orci=urna&luctus=pretium&et=nisl&ultrices=ut&posuere=volutpat&cubilia=sapien&curae=arcu&mauris=sed&viverra=augue&diam=aliquam&vitae=erat&quam=volutpat&suspendisse=in&potenti=congue&nullam=etiam&porttitor=justo&lacus=etiam&at=pretium', '2024-02-12T12:58:08Z');
insert into publishers (id, name, address, website, updated_at) values ('01J7W0QK1XW7WR21N2XQT652JD', 'Rohan-Hammes', '84 Mayer Court', 'https://usgs.gov/imperdiet/nullam/orci/pede/venenatis/non/sodales.jpg?odio=sapien&in=in&hac=sapien&habitasse=iaculis&platea=congue&dictumst=vivamus&maecenas=metus&ut=arcu&massa=adipiscing&quis=molestie&augue=hendrerit&luctus=at&tincidunt=vulputate&nulla=vitae&mollis=nisl&molestie=aenean&lorem=lectus&quisque=pellentesque&ut=eget&erat=nunc&curabitur=donec&gravida=quis&nisi=orci&at=eget&nibh=orci&in=vehicula&hac=condimentum&habitasse=curabitur&platea=in&dictumst=libero&aliquam=ut&augue=massa&quam=volutpat&sollicitudin=convallis&vitae=morbi&consectetuer=odio&eget=odio&rutrum=elementum&at=eu&lorem=interdum&integer=eu&tincidunt=tincidunt&ante=in&vel=leo&ipsum=maecenas&praesent=pulvinar&blandit=lobortis&lacinia=est&erat=phasellus&vestibulum=sit&sed=amet&magna=erat&at=nulla&nunc=tempus&commodo=vivamus&placerat=in&praesent=felis&blandit=eu&nam=sapien&nulla=cursus&integer=vestibulum&pede=proin&justo=eu&lacinia=mi&eget=nulla&tincidunt=ac&eget=enim&tempus=in&vel=tempor&pede=turpis&morbi=nec&porttitor=euismod&lorem=scelerisque&id=quam&ligula=turpis&suspendisse=adipiscing&ornare=lorem&consequat=vitae&lectus=mattis&in=nibh&est=ligula&risus=nec&auctor=sem&sed=duis', '2024-03-01T00:10:28Z');
insert into publishers (id, name, address, website, updated_at) values ('01J7W0QK1Y3EWB7KCA4VACDM40', 'Heathcote Inc', '096 Esch Road', 'http://deliciousdays.com/morbi/ut/odio/cras/mi/pede.xml?et=integer&tempus=ac&semper=leo&est=pellentesque&quam=ultrices&pharetra=mattis&magna=odio&ac=donec&consequat=vitae&metus=nisi&sapien=nam&ut=ultrices&nunc=libero&vestibulum=non&ante=mattis&ipsum=pulvinar&primis=nulla&in=pede&faucibus=ullamcorper&orci=augue&luctus=a&et=suscipit&ultrices=nulla&posuere=elit&cubilia=ac&curae=nulla&mauris=sed&viverra=vel&diam=enim&vitae=sit&quam=amet&suspendisse=nunc&potenti=viverra&nullam=dapibus&porttitor=nulla&lacus=suscipit&at=ligula&turpis=in&donec=lacus&posuere=curabitur&metus=at&vitae=ipsum&ipsum=ac', '2024-03-29T01:33:19Z');
insert into publishers (id, name, address, website, updated_at) values ('01J7W0QK1Y8XNY8HYKV7AMXDY6', 'O''Reilly, Barrows and Stoltenberg', '11 Cascade Crossing', 'https://163.com/eleifend/quam/a/odio/in/hac/habitasse.js?pede=mauris&justo=vulputate&lacinia=elementum&eget=nullam&tincidunt=varius&eget=nulla&tempus=facilisi&vel=cras&pede=non&morbi=velit&porttitor=nec&lorem=nisi&id=vulputate&ligula=nonummy&suspendisse=maecenas&ornare=tincidunt&consequat=lacus&lectus=at&in=velit&est=vivamus&risus=vel&auctor=nulla&sed=eget&tristique=eros&in=elementum&tempus=pellentesque&sit=quisque&amet=porta&sem=volutpat&fusce=erat&consequat=quisque&nulla=erat&nisl=eros&nunc=viverra&nisl=eget&duis=congue&bibendum=eget&felis=semper&sed=rutrum&interdum=nulla&venenatis=nunc&turpis=purus&enim=phasellus&blandit=in', '2024-03-22T16:10:46Z');
insert into publishers (id, name, address, website, updated_at) values ('01J7W0QK1ZNKC58MFW1H53SMC3', 'Keebler, Leffler and Yost', '773 Eggendart Place', 'https://zdnet.com/sapien/cum/sociis.xml?pharetra=lacus&magna=at&ac=turpis&consequat=donec&metus=posuere&sapien=metus&ut=vitae&nunc=ipsum&vestibulum=aliquam&ante=non&ipsum=mauris&primis=morbi&in=non&faucibus=lectus&orci=aliquam&luctus=sit&et=amet&ultrices=diam&posuere=in&cubilia=magna&curae=bibendum&mauris=imperdiet&viverra=nullam&diam=orci&vitae=pede&quam=venenatis&suspendisse=non&potenti=sodales&nullam=sed&porttitor=tincidunt&lacus=eu', '2024-06-07T23:46:25Z');
insert into publishers (id, name, address, website, updated_at) values ('01J7W0QK206DAHVKSTQ9VYNXWR', 'Stroman-Kuhn', '847 Loftsgordon Road', 'https://cbslocal.com/erat.jsp?ornare=lectus&consequat=in&lectus=quam&in=fringilla&est=rhoncus&risus=mauris&auctor=enim&sed=leo&tristique=rhoncus&in=sed&tempus=vestibulum&sit=sit&amet=amet&sem=cursus&fusce=id&consequat=turpis&nulla=integer&nisl=aliquet&nunc=massa&nisl=id&duis=lobortis&bibendum=convallis&felis=tortor&sed=risus&interdum=dapibus&venenatis=augue&turpis=vel&enim=accumsan&blandit=tellus&mi=nisi&in=eu&porttitor=orci&pede=mauris&justo=lacinia&eu=sapien&massa=quis&donec=libero&dapibus=nullam&duis=sit&at=amet&velit=turpis&eu=elementum&est=ligula&congue=vehicula&elementum=consequat&in=morbi&hac=a&habitasse=ipsum&platea=integer&dictumst=a&morbi=nibh&vestibulum=in&velit=quis&id=justo&pretium=maecenas&iaculis=rhoncus&diam=aliquam&erat=lacus&fermentum=morbi&justo=quis', '2024-07-07T22:12:16Z');
insert into publishers (id, name, address, website, updated_at) values ('01J7W0QK213PWESSYCA8PR9XN4', 'Langosh, Gulgowski and Bartell', '5 Evergreen Street', 'https://abc.net.au/semper.jpg?libero=erat&nullam=fermentum&sit=justo&amet=nec&turpis=condimentum&elementum=neque&ligula=sapien&vehicula=placerat&consequat=ante&morbi=nulla&a=justo&ipsum=aliquam&integer=quis&a=turpis&nibh=eget&in=elit&quis=sodales&justo=scelerisque&maecenas=mauris&rhoncus=sit&aliquam=amet&lacus=eros&morbi=suspendisse&quis=accumsan&tortor=tortor&id=quis&nulla=turpis&ultrices=sed&aliquet=ante&maecenas=vivamus&leo=tortor&odio=duis&condimentum=mattis&id=egestas&luctus=metus&nec=aenean&molestie=fermentum&sed=donec&justo=ut&pellentesque=mauris&viverra=eget&pede=massa&ac=tempor&diam=convallis&cras=nulla&pellentesque=neque&volutpat=libero&dui=convallis&maecenas=eget&tristique=eleifend&est=luctus&et=ultricies&tempus=eu&semper=nibh&est=quisque&quam=id&pharetra=justo&magna=sit&ac=amet&consequat=sapien&metus=dignissim&sapien=vestibulum&ut=vestibulum&nunc=ante&vestibulum=ipsum&ante=primis&ipsum=in&primis=faucibus&in=orci&faucibus=luctus&orci=et&luctus=ultrices', '2024-01-23T23:47:48Z');
insert into publishers (id, name, address, website, updated_at) values ('01J7W0QK21NKBPZQW2WZ4PHM8C', 'Stiedemann, Kuhn and Kemmer', '0778 Fallview Crossing', 'http://mapquest.com/tempor/turpis.aspx?nisi=vulputate&vulputate=justo&nonummy=in&maecenas=blandit&tincidunt=ultrices&lacus=enim&at=lorem&velit=ipsum&vivamus=dolor&vel=sit&nulla=amet&eget=consectetuer&eros=adipiscing&elementum=elit&pellentesque=proin&quisque=interdum&porta=mauris&volutpat=non&erat=ligula&quisque=pellentesque&erat=ultrices&eros=phasellus&viverra=id&eget=sapien&congue=in&eget=sapien&semper=iaculis&rutrum=congue&nulla=vivamus&nunc=metus&purus=arcu&phasellus=adipiscing&in=molestie&felis=hendrerit&donec=at&semper=vulputate&sapien=vitae&a=nisl&libero=aenean&nam=lectus&dui=pellentesque&proin=eget&leo=nunc&odio=donec&porttitor=quis&id=orci&consequat=eget&in=orci&consequat=vehicula&ut=condimentum&nulla=curabitur&sed=in&accumsan=libero&felis=ut&ut=massa&at=volutpat&dolor=convallis&quis=morbi&odio=odio&consequat=odio&varius=elementum&integer=eu&ac=interdum&leo=eu&pellentesque=tincidunt&ultrices=in&mattis=leo&odio=maecenas&donec=pulvinar&vitae=lobortis&nisi=est&nam=phasellus&ultrices=sit&libero=amet&non=erat&mattis=nulla&pulvinar=tempus&nulla=vivamus&pede=in&ullamcorper=felis', '2023-10-17T04:01:31Z');
insert into publishers (id, name, address, website, updated_at) values ('01J7W0QK22ZENKYHZD90FVE5T4', 'O''Reilly LLC', '85989 Vidon Crossing', 'http://hubpages.com/aliquet/pulvinar.jsp?egestas=cursus&metus=id&aenean=turpis&fermentum=integer&donec=aliquet&ut=massa&mauris=id&eget=lobortis&massa=convallis&tempor=tortor&convallis=risus&nulla=dapibus&neque=augue&libero=vel&convallis=accumsan&eget=tellus&eleifend=nisi&luctus=eu&ultricies=orci&eu=mauris&nibh=lacinia&quisque=sapien&id=quis&justo=libero&sit=nullam&amet=sit&sapien=amet&dignissim=turpis&vestibulum=elementum&vestibulum=ligula&ante=vehicula&ipsum=consequat&primis=morbi&in=a&faucibus=ipsum&orci=integer&luctus=a&et=nibh&ultrices=in&posuere=quis&cubilia=justo&curae=maecenas&nulla=rhoncus&dapibus=aliquam&dolor=lacus&vel=morbi&est=quis&donec=tortor&odio=id&justo=nulla&sollicitudin=ultrices&ut=aliquet&suscipit=maecenas&a=leo&feugiat=odio&et=condimentum&eros=id&vestibulum=luctus&ac=nec&est=molestie&lacinia=sed&nisi=justo&venenatis=pellentesque&tristique=viverra&fusce=pede', '2023-12-30T07:43:06Z');

-- Tags Table

insert into tags (id, name, type) values ('01J7W0XVNX0PSK4PTCKS2Q9XR8', 'capability', 'access');
insert into tags (id, name, type) values ('01J7W0XVNYW1YNSMJE718VBKR7', 'orchestration', 'Expanded');
insert into tags (id, name, type) values ('01J7W0XVNZGXJDYYHE3PRZK4EW', 'User-friendly', 'didactic');
insert into tags (id, name, type) values ('01J7W0XVNZ989DW1J13GF37SFW', 'Optional', 'Synergistic');
insert into tags (id, name, type) values ('01J7W0XVP03PS6485B0HXDFR04', 'Up-sized', 'fresh-thinking');
insert into tags (id, name, type) values ('01J7W0XVP0SH59WZB6BCXQJJR6', 'Total', 'Stand-alone');
insert into tags (id, name, type) values ('01J7W0XVP0ST2A5V6E0TB5HSSH', 'workforce', 'background');
insert into tags (id, name, type) values ('01J7W0XVP1MHXND15STT37G9NA', 'Multi-tiered', 'Multi-lateral');
insert into tags (id, name, type) values ('01J7W0XVP1XMHYSN2K26WPZ0RH', 'application', 'capability');
insert into tags (id, name, type) values ('01J7W0XVP1Y6JA0773371QHA0Z', 'synergy', 'Expanded');

-- Categories Table

insert into categories (id, name, type, description) values ('01J7W0WVDPCADAMHGH12MMYP8Y', 'functionalities', 'support', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into categories (id, name, type, description) values ('01J7W0WVDQQNCX4JZVSYF6Q21Y', 'generation', 'customer loyalty', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.');
insert into categories (id, name, type, description) values ('01J7W0WVDRABJB9GABRN14MJ4S', 'encryption', 'website', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into categories (id, name, type, description) values ('01J7W0WVDRDGAB5J28F11H9FC4', 'Multi-lateral', 'Decentralized', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into categories (id, name, type, description) values ('01J7W0WVDSDE2P39A0XW9J83BB', 'engineered', 'multi-state', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into categories (id, name, type, description) values ('01J7W0WVDSJPT8R5AFX6FCNKWZ', 'stable', 'Optimized', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into categories (id, name, type, description) values ('01J7W0WVDTC2R7G330FS3HKABD', '3rd generation', 'well-modulated', 'In congue. Etiam justo. Etiam pretium iaculis justo.');
insert into categories (id, name, type, description) values ('01J7W0WVDT673J9J0JTXT403ME', 'leading edge', '3rd generation', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into categories (id, name, type, description) values ('01J7W0WVDVFK2F5FM6G891TBBM', 'approach', 'mobile', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into categories (id, name, type, description) values ('01J7W0WVDV7HFK78TMJSM7CS9E', 'Re-engineered', 'middleware', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');

-- book_author

insert into book_author (book_id, author_id) values ('01J7W030NT4ZGQEXB6X8241VPG', '01J7W089DNEHP4DTR8RVXSENA3');
insert into book_author (book_id, author_id) values ('01J7W030NT4ZGQEXB6X8241VPG', '01J7W089DP1JVAA1MKESKGKWHA');
insert into book_author (book_id, author_id) values ('01J7W030W6G4C92QX73SZ8HW3A', '01J7W089DP1JVAA1MKESKGKWHA');
insert into book_author (book_id, author_id) values ('01J7W030W86V1WTVBYSRP79APE', '01J7W089DQ0GJV81NSA9J4W1G9');
insert into book_author (book_id, author_id) values ('01J7W030W97E1XPTFS0ZCF5Y9P', '01J7W089DR4MSS93FM1B2PPK1N');
insert into book_author (book_id, author_id) values ('01J7W030WB33P57PYTK6R7WRR7', '01J7W089DSSBMZFV81KQ0HSE1X');
insert into book_author (book_id, author_id) values ('01J7W030WB33P57PYTK6R7WRR7', '01J7W089DW2A8ZKA7NF4WN14FB');
insert into book_author (book_id, author_id) values ('01J7W030WE7PFAM58P3DBAHYEM', '01J7W089DT8CZFDAQTSMA1TP9S');
insert into book_author (book_id, author_id) values ('01J7W030WG1MQ7NEZEMY3Q0D9Z', '01J7W089DV74SHZJAGMXP32VE5');
insert into book_author (book_id, author_id) values ('01J7W030WJY05V9C8TSQ7T7F8B', '01J7W089DW2A8ZKA7NF4WN14FB');
insert into book_author (book_id, author_id) values ('01J7W030WMH7SPERF9PDZ4B27W', '01J7W089DXVYK3Z07M6HYN4XKF');
insert into book_author (book_id, author_id) values ('01J7W030WPC54NW84W3EATZ714', '01J7W089DY4BER9XYFQN4MNYFB');

-- book_publisher

insert into book_publisher (book_id, publisher_id) values ('01J7W030NT4ZGQEXB6X8241VPG', '01J7W0QK1V8415VZ4X8NFFD9ME');
insert into book_publisher (book_id, publisher_id) values ('01J7W030W6G4C92QX73SZ8HW3A', '01J7W0QK1WF4SQ43493203945Z');
insert into book_publisher (book_id, publisher_id) values ('01J7W030W86V1WTVBYSRP79APE', '01J7W0QK1XW7WR21N2XQT652JD');
insert into book_publisher (book_id, publisher_id) values ('01J7W030W86V1WTVBYSRP79APE', '01J7W0QK1Y3EWB7KCA4VACDM40');
insert into book_publisher (book_id, publisher_id) values ('01J7W030W97E1XPTFS0ZCF5Y9P', '01J7W0QK1Y3EWB7KCA4VACDM40');
insert into book_publisher (book_id, publisher_id) values ('01J7W030WB33P57PYTK6R7WRR7', '01J7W0QK1Y8XNY8HYKV7AMXDY6');
insert into book_publisher (book_id, publisher_id) values ('01J7W030WE7PFAM58P3DBAHYEM', '01J7W0QK1ZNKC58MFW1H53SMC3');
insert into book_publisher (book_id, publisher_id) values ('01J7W030WG1MQ7NEZEMY3Q0D9Z', '01J7W0QK206DAHVKSTQ9VYNXWR');
insert into book_publisher (book_id, publisher_id) values ('01J7W030WJY05V9C8TSQ7T7F8B', '01J7W0QK213PWESSYCA8PR9XN4');
insert into book_publisher (book_id, publisher_id) values ('01J7W030WMH7SPERF9PDZ4B27W', '01J7W0QK21NKBPZQW2WZ4PHM8C');
insert into book_publisher (book_id, publisher_id) values ('01J7W030WPC54NW84W3EATZ714', '01J7W0QK22ZENKYHZD90FVE5T4');
insert into book_publisher (book_id, publisher_id) values ('01J7W030WPC54NW84W3EATZ714', '01J7W0QK213PWESSYCA8PR9XN4');

-- book_tag

insert into book_tag (book_id, tag_id) values ('01J7W030NT4ZGQEXB6X8241VPG', '01J7W0XVNX0PSK4PTCKS2Q9XR8');
insert into book_tag (book_id, tag_id) values ('01J7W030NT4ZGQEXB6X8241VPG', '01J7W0XVNYW1YNSMJE718VBKR7');
insert into book_tag (book_id, tag_id) values ('01J7W030W6G4C92QX73SZ8HW3A', '01J7W0XVNYW1YNSMJE718VBKR7');
insert into book_tag (book_id, tag_id) values ('01J7W030W86V1WTVBYSRP79APE', '01J7W0XVNZGXJDYYHE3PRZK4EW');
insert into book_tag (book_id, tag_id) values ('01J7W030W97E1XPTFS0ZCF5Y9P', '01J7W0XVNZ989DW1J13GF37SFW');
insert into book_tag (book_id, tag_id) values ('01J7W030W97E1XPTFS0ZCF5Y9P', '01J7W0XVP03PS6485B0HXDFR04');
insert into book_tag (book_id, tag_id) values ('01J7W030WB33P57PYTK6R7WRR7', '01J7W0XVP03PS6485B0HXDFR04');
insert into book_tag (book_id, tag_id) values ('01J7W030WE7PFAM58P3DBAHYEM', '01J7W0XVP0SH59WZB6BCXQJJR6');
insert into book_tag (book_id, tag_id) values ('01J7W030WG1MQ7NEZEMY3Q0D9Z', '01J7W0XVP0ST2A5V6E0TB5HSSH');
insert into book_tag (book_id, tag_id) values ('01J7W030WG1MQ7NEZEMY3Q0D9Z', '01J7W0XVP1XMHYSN2K26WPZ0RH');
insert into book_tag (book_id, tag_id) values ('01J7W030WJY05V9C8TSQ7T7F8B', '01J7W0XVP1MHXND15STT37G9NA');
insert into book_tag (book_id, tag_id) values ('01J7W030WMH7SPERF9PDZ4B27W', '01J7W0XVP1XMHYSN2K26WPZ0RH');
insert into book_tag (book_id, tag_id) values ('01J7W030WPC54NW84W3EATZ714', '01J7W0XVP1Y6JA0773371QHA0Z');
insert into book_tag (book_id, tag_id) values ('01J7W030WPC54NW84W3EATZ714', '01J7W0XVP1XMHYSN2K26WPZ0RH');

-- book_category

insert into book_category (book_id, category_id) values ('01J7W030NT4ZGQEXB6X8241VPG', '01J7W0WVDPCADAMHGH12MMYP8Y');
insert into book_category (book_id, category_id) values ('01J7W030NT4ZGQEXB6X8241VPG', '01J7W0WVDRABJB9GABRN14MJ4S');
insert into book_category (book_id, category_id) values ('01J7W030W6G4C92QX73SZ8HW3A', '01J7W0WVDQQNCX4JZVSYF6Q21Y');
insert into book_category (book_id, category_id) values ('01J7W030W86V1WTVBYSRP79APE', '01J7W0WVDRABJB9GABRN14MJ4S');
insert into book_category (book_id, category_id) values ('01J7W030W97E1XPTFS0ZCF5Y9P', '01J7W0WVDRDGAB5J28F11H9FC4');
insert into book_category (book_id, category_id) values ('01J7W030WB33P57PYTK6R7WRR7', '01J7W0WVDSDE2P39A0XW9J83BB');
insert into book_category (book_id, category_id) values ('01J7W030WB33P57PYTK6R7WRR7', '01J7W0WVDTC2R7G330FS3HKABD');
insert into book_category (book_id, category_id) values ('01J7W030WE7PFAM58P3DBAHYEM', '01J7W0WVDSJPT8R5AFX6FCNKWZ');
insert into book_category (book_id, category_id) values ('01J7W030WG1MQ7NEZEMY3Q0D9Z', '01J7W0WVDTC2R7G330FS3HKABD');
insert into book_category (book_id, category_id) values ('01J7W030WJY05V9C8TSQ7T7F8B', '01J7W0WVDT673J9J0JTXT403ME');
insert into book_category (book_id, category_id) values ('01J7W030WJY05V9C8TSQ7T7F8B', '01J7W0WVDVFK2F5FM6G891TBBM');
insert into book_category (book_id, category_id) values ('01J7W030WMH7SPERF9PDZ4B27W', '01J7W0WVDVFK2F5FM6G891TBBM');
insert into book_category (book_id, category_id) values ('01J7W030WPC54NW84W3EATZ714', '01J7W0WVDV7HFK78TMJSM7CS9E');
